#!/usr/bin/env fish

set SOURCE_PATH "$argv[1]"
set SQUARE_SIDE (identify -format "%h" "$SOURCE_PATH")

echo "Slicing ""$SOURCE_PATH"" into ""$SQUARE_SIDE""px squares..."

convert -crop "$SQUARE_SIDE"x"$SQUARE_SIDE" "$SOURCE_PATH" "$SOURCE_PATH"_cropped_%d.tif
convert -background white -extent "$SQUARE_SIDE"x"$SQUARE_SIDE" "$SOURCE_PATH"_cropped_*.tif -quality 95 "$SOURCE_PATH"_slice_%d.jpg

echo "Done."
